/**********************************************************************************
 * $URL$
 * $Id$
 ***********************************************************************************
 *
 * Copyright (c) 2008 Timefields Ltd
 *
 * Licensed under the Educational Community License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/ecl1.php
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 **********************************************************************************/

package org.sakaiproject.sdata.tool.api;

/**
 * A respurce definition defines a resource associated with each request. It is
 * generated by a ResourceDefinitionFactory
 * 
 * @author ieb
 */
public interface ResourceDefinition
{

	/**
	 * Get the native path in the repository for the resource
	 * 
	 * @return
	 */
	String getRepositoryPath();

	/**
	 * Get the external path of the passed in path releative to this resource
	 * 
	 * @param path
	 * @return
	 */
	String getExternalPath(String path);

	/**
	 * Get the repository path, relative to this resource
	 * 
	 * @param name
	 * @return
	 */
	String getRepositoryPath(String name);

	/**
	 * Does the path represent a resource that is private for the current
	 * request This may relate to a logged in user or context. This will control
	 * the caching headers in the http response.
	 * 
	 * @return
	 */
	boolean isPrivate();

	/**
	 * @return
	 */
	String getFunctionDefinition();

	/**
	 * @return
	 */
	int getDepth();

}
